services:
  db:
    image: postgres:16
    container_name: navio-db
    environment:
      POSTGRES_DB: navio
      POSTGRES_USER: navio
      POSTGRES_PASSWORD: navio
    ports:
      - "5432:5432"
    volumes:
      - navio_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U navio -d navio"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: navio-backend
    environment:
      APP_ENV: dev
      LOG_LEVEL: INFO
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: navio
      POSTGRES_USER: navio
      POSTGRES_PASSWORD: navio
      JWT_SECRET: 1212
      JWT_ACCESS_TTL_MIN: 15
      LOGIN_CODE_TTL_MIN: 10
      LOGIN_CODE_PEPPER: 1212
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_USER: naviolearn@gmail.com
      SMTP_PASSWORD: "meew dcnz dszz uqul"
      SMTP_FROM_NAME: "Navio Learn"
      SMTP_FROM_EMAIL: naviolearn@gmail.com
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  navio_pgdata: